/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'post-categories': PostCategory;
    'post-tags': PostTag;
    posts: Post;
    'product-categories': ProductCategory;
    'product-tags': ProductTag;
    products: Product;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    'post-tags': PostTagsSelect<false> | PostTagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    'product-tags': ProductTagsSelect<false> | ProductTagsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'payment-settings': PaymentSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payment-settings': PaymentSettingsSelect<false> | PaymentSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'ops' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  blocks?:
    | {
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  sections?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items: {
              title: string;
              body?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            heading?: string | null;
            items: {
              value: string;
              label: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading: string;
            description?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-tags".
 */
export interface PostTag {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  /**
   * 博客列表、详情页和内容筛选默认使用这个主分类。
   */
  primaryCategory?: (number | null) | PostCategory;
  /**
   * 可用于扩展筛选、专题聚合和首页内容编排。
   */
  categories?: (number | PostCategory)[] | null;
  /**
   * 适合观点、专题、阶段标签和跨分类内容聚合。
   */
  tags?: (number | PostTag)[] | null;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tags".
 */
export interface ProductTag {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  summary?: string | null;
  /**
   * 商城列表和导购筛选默认使用这个主分类。
   */
  primaryCategory?: (number | null) | ProductCategory;
  /**
   * 可用于多分类归档、专题筛选和首页商品编排。
   */
  categories?: (number | ProductCategory)[] | null;
  /**
   * 适合库存策略、硬件能力、部署形态和运营标签。
   */
  tags?: (number | ProductTag)[] | null;
  /**
   * 给运营和履约使用的商品编号。
   */
  sku?: string | null;
  cover?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  price: number;
  currency: string;
  /**
   * 开启后，下单会按库存数校验可售数量。
   */
  trackInventory?: boolean | null;
  /**
   * 库存不足时仍允许继续接单。
   */
  allowBackorder?: boolean | null;
  /**
   * 当前可售库存总量。
   */
  stockQuantity?: number | null;
  /**
   * 单笔订单最多可购买数量，留空表示不限制。
   */
  limitPerOrder?: number | null;
  status: 'draft' | 'active' | 'archived';
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNo: string;
  status: 'pending' | 'paid' | 'failed' | 'cancelled' | 'refunded';
  source: 'shop' | 'landing' | 'manual';
  items: {
    product: number | Product;
    quantity: number;
    /**
     * 留空时会按当前商品价格自动回填。
     */
    unitPrice?: number | null;
    id?: string | null;
  }[];
  /**
   * 保存时会根据商品数量和单价自动计算总价。
   */
  totalAmount?: number | null;
  customerName?: string | null;
  customerPhone?: string | null;
  customerEmail?: string | null;
  shippingAddress?: string | null;
  /**
   * 后台运营备注，不对前台展示。
   */
  operatorNote?: string | null;
  fulfillmentStatus: 'pending' | 'processing' | 'shipped' | 'completed';
  deliveryMethod: 'digital' | 'shipping' | 'service';
  trackingNo?: string | null;
  /**
   * 给客户的交付备注或发货说明，可同步展示到前台订单详情。
   */
  deliveryNote?: string | null;
  fulfilledAt?: string | null;
  paymentProvider?: string | null;
  paymentStatus: 'unpaid' | 'processing' | 'paid' | 'failed' | 'refunded';
  paymentOrderNo?: string | null;
  paymentTradeNo?: string | null;
  paymentPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paidAt?: string | null;
  paymentLastError?: string | null;
  /**
   * 支付发起、回调、验签和失败信息都会记录在这里，便于联调排查。
   */
  paymentEvents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 用于原生订单列表和工作台的链路筛选标签。
   */
  paymentChainTags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paymentHasIssue?: boolean | null;
  paymentHasNotifyIssue?: boolean | null;
  paymentHasReturnRecord?: boolean | null;
  paymentHasQueryRecord?: boolean | null;
  paymentHasFinalResult?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'post-tags';
        value: number | PostTag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'product-tags';
        value: number | ProductTag;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  blocks?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-tags_select".
 */
export interface PostTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  primaryCategory?: T;
  categories?: T;
  tags?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tags_select".
 */
export interface ProductTagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  summary?: T;
  primaryCategory?: T;
  categories?: T;
  tags?: T;
  sku?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  price?: T;
  currency?: T;
  trackInventory?: T;
  allowBackorder?: T;
  stockQuantity?: T;
  limitPerOrder?: T;
  status?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNo?: T;
  status?: T;
  source?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  totalAmount?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  shippingAddress?: T;
  operatorNote?: T;
  fulfillmentStatus?: T;
  deliveryMethod?: T;
  trackingNo?: T;
  deliveryNote?: T;
  fulfilledAt?: T;
  paymentProvider?: T;
  paymentStatus?: T;
  paymentOrderNo?: T;
  paymentTradeNo?: T;
  paymentPayload?: T;
  paidAt?: T;
  paymentLastError?: T;
  paymentEvents?: T;
  paymentChainTags?: T;
  paymentHasIssue?: T;
  paymentHasNotifyIssue?: T;
  paymentHasReturnRecord?: T;
  paymentHasQueryRecord?: T;
  paymentHasFinalResult?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteUrl?: string | null;
  logo?: (number | null) | Media;
  primaryColor?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  contactEmail?: string | null;
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  home: {
    eyebrow?: string | null;
    heroTitle: string;
    heroDescription?: string | null;
    primaryActionLabel?: string | null;
    primaryActionHref?: string | null;
    secondaryActionLabel?: string | null;
    secondaryActionHref?: string | null;
    panelEyebrow?: string | null;
    panelTitle?: string | null;
    panelBody?: string | null;
    panelMetrics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    featuredPagesHeading?: string | null;
    featuredPagesDescription?: string | null;
    featuredPages?: (number | Page)[] | null;
    featuredPostsHeading?: string | null;
    featuredPostsDescription?: string | null;
    featuredPosts?: (number | Post)[] | null;
    featuredProductsHeading?: string | null;
    featuredProductsDescription?: string | null;
    featuredProducts?: (number | Product)[] | null;
    ctaEyebrow?: string | null;
    ctaTitle?: string | null;
    ctaDescription?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings".
 */
export interface PaymentSetting {
  id: number;
  /**
   * 当前站点仅接入支付宝支付。
   */
  provider?: 'alipay' | null;
  /**
   * 支付宝异步通知地址。若同时配置了环境变量，环境变量优先。
   */
  notifyUrl?: string | null;
  /**
   * 支付宝同步返回地址。建议保持线上 HTTPS 地址。
   */
  returnUrl?: string | null;
  /**
   * 支付宝应用 App ID。真实联调前，可用 /payment-diagnostics 检查当前服务端是否已识别。
   */
  appId?: string | null;
  /**
   * 支付宝收款账号对应的 seller_id。配置后可用于异步通知的业务校验。
   */
  sellerId?: string | null;
  /**
   * 默认使用支付宝生产网关。仅在特殊环境下调整。
   */
  gateway?: string | null;
  /**
   * 应用私钥。敏感配置更推荐使用环境变量注入；后台填写时仅限 ops / super-admin。
   */
  privateKey?: string | null;
  /**
   * 支付宝公钥，用于 notify 验签。未配置时，异步通知无法完成验签回写。
   */
  publicKey?: string | null;
  /**
   * 后台回退值是否已保存应用私钥。
   */
  privateKeyConfigured?: boolean | null;
  /**
   * 当前后台私钥行数摘要。
   */
  privateKeyLineCount?: number | null;
  /**
   * 后台回退值是否已保存支付宝公钥。
   */
  publicKeyConfigured?: boolean | null;
  /**
   * 当前后台公钥行数摘要。
   */
  publicKeyLineCount?: number | null;
  /**
   * 最近一次通过后台更新密钥的时间。
   */
  keysUpdatedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  logo?: T;
  primaryColor?: T;
  seoTitle?: T;
  seoDescription?: T;
  contactEmail?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  home?:
    | T
    | {
        eyebrow?: T;
        heroTitle?: T;
        heroDescription?: T;
        primaryActionLabel?: T;
        primaryActionHref?: T;
        secondaryActionLabel?: T;
        secondaryActionHref?: T;
        panelEyebrow?: T;
        panelTitle?: T;
        panelBody?: T;
        panelMetrics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        featuredPagesHeading?: T;
        featuredPagesDescription?: T;
        featuredPages?: T;
        featuredPostsHeading?: T;
        featuredPostsDescription?: T;
        featuredPosts?: T;
        featuredProductsHeading?: T;
        featuredProductsDescription?: T;
        featuredProducts?: T;
        ctaEyebrow?: T;
        ctaTitle?: T;
        ctaDescription?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings_select".
 */
export interface PaymentSettingsSelect<T extends boolean = true> {
  provider?: T;
  notifyUrl?: T;
  returnUrl?: T;
  appId?: T;
  sellerId?: T;
  gateway?: T;
  privateKey?: T;
  publicKey?: T;
  privateKeyConfigured?: T;
  privateKeyLineCount?: T;
  publicKeyConfigured?: T;
  publicKeyLineCount?: T;
  keysUpdatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}