module.exports = {
  apps: [
    {
      name: 'payload-geekclaw',
      cwd: __dirname,
      script: 'npm',
      args: 'run start',
      interpreter: 'none',
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        PORT: '26223',
        PAYLOAD_SECRET: 'change-me',
        DATABASE_URI: 'file:./.payload/geekclaw.db',
        NEXT_PUBLIC_SITE_URL: 'https://geekclaw.ai',
        CRON_SECRET: 'change-me-too',
        ALIPAY_APP_ID: '',
        ALIPAY_PRIVATE_KEY: '',
        ALIPAY_PUBLIC_KEY: '',
        ALIPAY_GATEWAY: 'https://openapi.alipay.com/gateway.do',
        ALIPAY_NOTIFY_URL: 'https://geekclaw.ai/api/pay/alipay/notify',
        ALIPAY_RETURN_URL: 'https://geekclaw.ai/pay-success',
      },
    },
    {
      name: 'payload-orders-maintenance',
      cwd: __dirname,
      script: 'npm',
      args: 'run orders:maintenance',
      interpreter: 'none',
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        CLOSE_EXPIRED_BASE_URL: 'http://127.0.0.1:26223',
        SYNC_PROCESSING_BASE_URL: 'http://127.0.0.1:26223',
        CLOSE_EXPIRED_INTERVAL_MINUTES: '5',
        SYNC_PROCESSING_INTERVAL_MINUTES: '10',
        SYNC_PROCESSING_LIMIT: '20',
        ORDERS_MAINTENANCE_STARTUP_DELAY_SECONDS: '45',
        CRON_SECRET: 'change-me-too',
      },
    },
  ],
}
